"""V2 Loop 4 — E-6 Carson/Drum winter, E-5 Bliss/JBLM childcare, O-4 Gordon/Campbell nurse."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_K = {
    "e6_carson_drum_winter": {
        "first_name": "Nate",
        "last_name": "Bergman",
        "email": "loop@example.com",
        "rank_pay_grade": "E-6",
        "rank_title": rank_for_pay_grade("E-6"),
        "current_installation_preset": "Fort Carson, CO",
        "gaining_installation": "Fort Drum, NY",
        "move_window": "1–3 months",
        "spouse_career_field": "Federal / government civilian",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1800,
        "housing_must_haves_selected": ["Good school district"],
        "primary_priority": "School quality",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Winter weather / heating costs"],
    },
    "e5_bliss_jblm_childcare": {
        "first_name": "Jasmine",
        "last_name": "Reed",
        "email": "loop@example.com",
        "rank_pay_grade": "E-5",
        "rank_title": rank_for_pay_grade("E-5"),
        "current_installation_preset": "Fort Bliss, TX",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "move_window": "1–3 months",
        "spouse_career_field": "Not currently working — seeking employment",
        "num_children": 2,
        "child_age_ranges": ["Infant/toddler (0–2)", "Preschool (3–5)"],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1700,
        "primary_priority": "Fastest possible resettlement",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Need childcare immediately on arrival", "Tight PCS timeline"],
    },
    "o4_gordon_campbell_nurse": {
        "first_name": "Heather",
        "last_name": "Sloan",
        "email": "loop@example.com",
        "rank_pay_grade": "O-4",
        "rank_title": rank_for_pay_grade("O-4"),
        "current_installation_preset": "Fort Gordon, GA",
        "gaining_installation": "Fort Campbell, KY",
        "move_window": "3–6 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 1,
        "child_age_ranges": ["Preschool (3–5)"],
        "has_pets": "No pets",
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2100,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "School quality",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Professional licensure transfer", "Need childcare immediately on arrival"],
    },
}