"""Warmth loop 4 — E-3 student spouse, W-3 trades, O-5 winter move."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_P = {
    "e3_bliss_jblm_student": {
        "first_name": "Miguel",
        "last_name": "Santos",
        "email": "loop@example.com",
        "rank_pay_grade": "E-3",
        "rank_title": rank_for_pay_grade("E-3"),
        "current_installation_preset": "Fort Bliss, TX",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "move_window": "3–6 months",
        "spouse_career_field": "Student / continuing education",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1550,
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Winter weather / heating costs"],
    },
    "w3_leavenworth_stewart_trades": {
        "first_name": "Patricia",
        "last_name": "Nguyen",
        "email": "loop@example.com",
        "rank_pay_grade": "W-3",
        "rank_title": rank_for_pay_grade("W-3"),
        "current_installation_preset": "Fort Leavenworth, KS",
        "gaining_installation": "Fort Stewart, GA",
        "move_window": "1–3 months",
        "spouse_career_field": "Trades / skilled labor",
        "num_children": 2,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Cat(s)"],
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2000,
        "housing_must_haves_selected": ["Pet-friendly", "Garage / covered parking"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Pet deposit / breed restrictions"],
    },
    "o5_carson_drum_winter": {
        "first_name": "Greg",
        "last_name": "Walters",
        "email": "loop@example.com",
        "rank_pay_grade": "O-5",
        "rank_title": rank_for_pay_grade("O-5"),
        "current_installation_preset": "Fort Carson, CO",
        "gaining_installation": "Fort Drum, NY",
        "move_window": "1–3 months",
        "spouse_career_field": "Federal / government civilian",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2100,
        "housing_must_haves_selected": ["Good school district"],
        "primary_priority": "School quality",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Winter weather / heating costs"],
    },
}