"""V2 Loop 2 — W-2 Riley/Carson EFMP, E-5 Drum/Knox retail, O-5 Bliss/Campbell federal."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_I = {
    "w2_riley_carson_efmp": {
        "first_name": "Angela",
        "last_name": "Price",
        "email": "loop@example.com",
        "rank_pay_grade": "W-2",
        "rank_title": rank_for_pay_grade("W-2"),
        "current_installation_preset": "Fort Riley, KS",
        "gaining_installation": "Fort Carson, CO",
        "move_window": "1–3 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 1,
        "child_age_ranges": ["Preschool (3–5)"],
        "has_pets": "No pets",
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2000,
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["EFMP / medical care coordination", "Need childcare immediately on arrival"],
    },
    "e5_drum_knox_retail": {
        "first_name": "Tommy",
        "last_name": "Nguyen",
        "email": "loop@example.com",
        "rank_pay_grade": "E-5",
        "rank_title": rank_for_pay_grade("E-5"),
        "current_installation_preset": "Fort Drum, NY",
        "gaining_installation": "Fort Knox, KY",
        "move_window": "Within 30 days",
        "spouse_career_field": "Retail / hospitality / service",
        "num_children": 2,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1400,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "Fastest possible resettlement",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Tight PCS timeline", "Need childcare immediately on arrival"],
    },
    "o5_bliss_campbell_federal": {
        "first_name": "Greg",
        "last_name": "Walters",
        "email": "loop@example.com",
        "rank_pay_grade": "O-5",
        "rank_title": rank_for_pay_grade("O-5"),
        "current_installation_preset": "Fort Bliss, TX",
        "gaining_installation": "Fort Campbell, KY",
        "move_window": "3–6 months",
        "spouse_career_field": "Federal / government civilian",
        "num_children": 3,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)", "High school (14–18)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Cat(s)"],
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2500,
        "housing_must_haves_selected": ["Good school district", "4+ bedrooms", "Pet-friendly"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Professional licensure transfer"],
    },
}