"""Loop 1 profiles — Jackson/Knox, Gordon/Drum, Riley/Carson."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_B = {
    "e4_jackson_knox_retail": {
        "first_name": "Miguel",
        "last_name": "Santos",
        "email": "loop@example.com",
        "rank_pay_grade": "E-4",
        "rank_title": rank_for_pay_grade("E-4"),
        "current_installation_preset": "Fort Jackson, SC",
        "gaining_installation": "Fort Knox, KY",
        "move_window": "1–3 months",
        "move_flexibility": "Somewhat flexible (±2 weeks)",
        "spouse_career_field": "Retail / hospitality / service",
        "num_children": 1,
        "child_age_ranges": ["Preschool (3–5)"],
        "has_pets": "No pets",
        "pet_types": [],
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1300,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Gate traffic / commute sensitivity"],
    },
    "o4_gordon_drum_nurse": {
        "first_name": "Rachel",
        "last_name": "Kim",
        "email": "loop@example.com",
        "rank_pay_grade": "O-4",
        "rank_title": rank_for_pay_grade("O-4"),
        "current_installation_preset": "Fort Gordon, GA",
        "gaining_installation": "Fort Drum, NY",
        "move_window": "3–6 months",
        "move_flexibility": "Somewhat flexible (±2 weeks)",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1700,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Winter weather / heating costs", "Child has IEP / special education needs"],
        "specific_concerns": "One child has IEP — need district confirmation before lease",
    },
    "e6_riley_carson_federal": {
        "first_name": "Brian",
        "last_name": "Walsh",
        "email": "loop@example.com",
        "rank_pay_grade": "E-6",
        "rank_title": rank_for_pay_grade("E-6"),
        "current_installation_preset": "Fort Riley, KS",
        "gaining_installation": "Fort Carson, CO",
        "move_window": "Within 30 days",
        "move_flexibility": "Fixed — must align with reporting date",
        "spouse_career_field": "Federal / government civilian",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "High school (14–18)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Cat(s)"],
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2000,
        "housing_must_haves_selected": ["Pet-friendly", "4+ bedrooms"],
        "primary_priority": "Fastest possible resettlement",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Tight PCS timeline"],
    },
}