"""Warmth loop 3 — E-5 trades, E-7 teacher, O-4 nurse 3-kid."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_O = {
    "e5_sill_riley_trades": {
        "first_name": "Jordan",
        "last_name": "Pierce",
        "email": "loop@example.com",
        "rank_pay_grade": "E-5",
        "rank_title": rank_for_pay_grade("E-5"),
        "current_installation_preset": "Fort Sill, OK",
        "gaining_installation": "Fort Riley, KS",
        "move_window": "Within 30 days",
        "spouse_career_field": "Trades / skilled labor",
        "num_children": 1,
        "child_age_ranges": ["Elementary (6–10)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1600,
        "housing_must_haves_selected": ["Garage / covered parking", "Pet-friendly"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Tight PCS timeline"],
    },
    "e7_gordon_benning_teacher": {
        "first_name": "Karen",
        "last_name": "Sims",
        "email": "loop@example.com",
        "rank_pay_grade": "E-7",
        "rank_title": rank_for_pay_grade("E-7"),
        "current_installation_preset": "Fort Gordon, GA",
        "gaining_installation": "Fort Benning, GA",
        "move_window": "1–3 months",
        "spouse_career_field": "K-12 education / teaching",
        "num_children": 1,
        "child_age_ranges": ["High school (14–18)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1850,
        "housing_must_haves_selected": ["Good school district"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": [],
    },
    "o4_bragg_campbell_nurse": {
        "first_name": "David",
        "last_name": "Morris",
        "email": "loop@example.com",
        "rank_pay_grade": "O-4",
        "rank_title": rank_for_pay_grade("O-4"),
        "current_installation_preset": "Fort Bragg, NC",
        "gaining_installation": "Fort Campbell, KY",
        "move_window": "3–6 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 3,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2500,
        "housing_must_haves_selected": ["Good school district", "4+ bedrooms"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Professional licensure transfer", "Need childcare immediately on arrival"],
    },
}