"""Three profiles per improvement loop — varied rank, family, career, distance."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

IMPROVEMENT_BATCH_A = {
    "e5_hood_remote_short": {
        "first_name": "Tyler",
        "last_name": "Nguyen",
        "email": "improve@example.com",
        "rank_pay_grade": "E-5",
        "rank_title": rank_for_pay_grade("E-5"),
        "current_installation_preset": "Fort Drum, NY",
        "gaining_installation": "Fort Hood, TX",
        "move_window": "Within 30 days",
        "move_flexibility": "Fixed — must align with reporting date",
        "spouse_career_field": "Remote / work-from-home professional",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "pet_types": [],
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1500,
        "housing_must_haves_selected": ["Strong internet / remote-work ready"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Winter weather / heating costs"],
        "specific_concerns": "",
    },
    "e7_bragg_teacher_mid": {
        "first_name": "Keisha",
        "last_name": "Morris",
        "email": "improve@example.com",
        "rank_pay_grade": "E-7",
        "rank_title": rank_for_pay_grade("E-7"),
        "current_installation_preset": "Fort Campbell, KY",
        "gaining_installation": "Fort Bragg, NC",
        "move_window": "1–3 months",
        "spouse_career_field": "K-12 education / teaching",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1900,
        "housing_must_haves_selected": ["Fenced yard", "Good school district"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "School quality",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Professional licensure transfer", "Need childcare immediately on arrival"],
    },
    "o2_carson_nurse_long": {
        "first_name": "Luke",
        "last_name": "Fischer",
        "email": "improve@example.com",
        "rank_pay_grade": "O-2",
        "rank_title": rank_for_pay_grade("O-2"),
        "current_installation_preset": "Fort Carson, CO",
        "gaining_installation": "Fort Bliss, TX",
        "move_window": "3–6 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 1,
        "child_age_ranges": ["Infant (0–2)"],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2000,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "Fastest possible resettlement",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Need childcare immediately on arrival"],
    },
}