"""Loop 3 profiles — Sill/Hood, Campbell/Gordon, E-8 JBLM."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_D = {
    "e3_sill_hood_single": {
        "first_name": "Alex",
        "last_name": "Romero",
        "email": "loop@example.com",
        "rank_pay_grade": "E-3",
        "rank_title": rank_for_pay_grade("E-3"),
        "current_installation_preset": "Fort Sill, OK",
        "gaining_installation": "Fort Hood, TX",
        "move_window": "Within 30 days",
        "spouse_career_field": "Not currently working — seeking employment",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1200,
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": [],
    },
    "e7_campbell_gordon_teacher": {
        "first_name": "Lisa",
        "last_name": "Grant",
        "email": "loop@example.com",
        "rank_pay_grade": "E-7",
        "rank_title": rank_for_pay_grade("E-7"),
        "current_installation_preset": "Fort Campbell, KY",
        "gaining_installation": "Fort Gordon, GA",
        "move_window": "1–3 months",
        "spouse_career_field": "K-12 education / teaching",
        "num_children": 1,
        "child_age_ranges": ["High school (14–18)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1750,
        "housing_must_haves_selected": ["Good school district"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "School quality",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Professional licensure transfer"],
    },
    "e8_carson_jblm_efmp": {
        "first_name": "Marcus",
        "last_name": "Thompson",
        "email": "loop@example.com",
        "rank_pay_grade": "E-8",
        "rank_title": rank_for_pay_grade("E-8"),
        "current_installation_preset": "Fort Carson, CO",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "move_window": "3–6 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 1,
        "child_age_ranges": ["Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2400,
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["EFMP / medical care coordination", "Child has IEP / special education needs"],
        "specific_concerns": "EFMP son needs therapy continuity",
    },
}