"""Loop 4 profiles — Benning/Stewart, Hood/Campbell, Sill/Riley."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_E = {
    "e2_benning_stewart_pets": {
        "first_name": "Tyler",
        "last_name": "Brooks",
        "email": "loop@example.com",
        "rank_pay_grade": "E-2",
        "rank_title": rank_for_pay_grade("E-2"),
        "current_installation_preset": "Fort Benning, GA",
        "gaining_installation": "Fort Stewart, GA",
        "move_window": "Within 30 days",
        "spouse_career_field": "Not currently working — seeking employment",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1100,
        "housing_must_haves_selected": ["Pet-friendly"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Pet deposit / breed restrictions"],
    },
    "o5_hood_campbell_federal": {
        "first_name": "James",
        "last_name": "Harrington",
        "email": "loop@example.com",
        "rank_pay_grade": "O-5",
        "rank_title": rank_for_pay_grade("O-5"),
        "current_installation_preset": "Fort Hood, TX",
        "gaining_installation": "Fort Campbell, KY",
        "move_window": "3–6 months",
        "spouse_career_field": "Federal / government civilian",
        "num_children": 3,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)", "High school (14–18)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2400,
        "housing_must_haves_selected": ["Good school district", "4+ bedrooms"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Professional licensure transfer"],
    },
    "w2_sill_riley_iep": {
        "first_name": "Nina",
        "last_name": "Vasquez",
        "email": "loop@example.com",
        "rank_pay_grade": "W-2",
        "rank_title": rank_for_pay_grade("W-2"),
        "current_installation_preset": "Fort Sill, OK",
        "gaining_installation": "Fort Riley, KS",
        "move_window": "1–3 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1900,
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Child has IEP / special education needs", "EFMP / medical care coordination"],
        "specific_concerns": "Only our elementary child has an IEP — need district confirmation before lease",
    },
}