"""V2 Loop 5 — E-2 Knox/Benning short, W-3 Stewart/Bragg 3-kid, E-5 Leavenworth/Sill trades."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_L = {
    "e2_knox_benning_short": {
        "first_name": "Caleb",
        "last_name": "Wright",
        "email": "loop@example.com",
        "rank_pay_grade": "E-2",
        "rank_title": rank_for_pay_grade("E-2"),
        "current_installation_preset": "Fort Knox, KY",
        "gaining_installation": "Fort Benning, GA",
        "move_window": "Within 30 days",
        "spouse_career_field": "Retail / hospitality / service",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1100,
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Tight PCS timeline"],
    },
    "w3_stewart_bragg_childcare": {
        "first_name": "Donna",
        "last_name": "Fischer",
        "email": "loop@example.com",
        "rank_pay_grade": "W-3",
        "rank_title": rank_for_pay_grade("W-3"),
        "current_installation_preset": "Fort Stewart, GA",
        "gaining_installation": "Fort Bragg, NC",
        "move_window": "1–3 months",
        "spouse_career_field": "K-12 education / teaching",
        "num_children": 3,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Cat(s)"],
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2300,
        "housing_must_haves_selected": ["Good school district", "4+ bedrooms", "Pet-friendly"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Need childcare immediately on arrival", "Pet deposit / breed restrictions"],
    },
    "e5_leavenworth_sill_trades": {
        "first_name": "Oscar",
        "last_name": "Mendez",
        "email": "loop@example.com",
        "rank_pay_grade": "E-5",
        "rank_title": rank_for_pay_grade("E-5"),
        "current_installation_preset": "Fort Leavenworth, KS",
        "gaining_installation": "Fort Sill, OK",
        "move_window": "3–6 months",
        "spouse_career_field": "Trades / skilled labor",
        "num_children": 1,
        "child_age_ranges": ["Elementary (6–10)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1500,
        "housing_must_haves_selected": ["Garage / covered parking"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Gate traffic / commute sensitivity"],
    },
}