"""Loop 5 profiles — JBLM/Benning, Knox/Bliss, Drum/Leavenworth."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_F = {
    "e5_jblm_benning_retail": {
        "first_name": "Chris",
        "last_name": "Dalton",
        "email": "loop@example.com",
        "rank_pay_grade": "E-5",
        "rank_title": rank_for_pay_grade("E-5"),
        "current_installation_preset": "Joint Base Lewis-McChord, WA",
        "gaining_installation": "Fort Benning, GA",
        "move_window": "Within 30 days",
        "spouse_career_field": "Retail / hospitality / service",
        "num_children": 2,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1500,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "Fastest possible resettlement",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Tight PCS timeline", "Need childcare immediately on arrival"],
    },
    "o2_knox_bliss_remote": {
        "first_name": "Sarah",
        "last_name": "Mitchell",
        "email": "loop@example.com",
        "rank_pay_grade": "O-2",
        "rank_title": rank_for_pay_grade("O-2"),
        "current_installation_preset": "Fort Knox, KY",
        "gaining_installation": "Fort Bliss, TX",
        "move_window": "1–3 months",
        "spouse_career_field": "Remote / work-from-home professional",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1800,
        "housing_must_haves_selected": ["Strong internet / remote-work ready"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Gate traffic / commute sensitivity"],
    },
    "e7_drum_leavenworth_teacher": {
        "first_name": "Kevin",
        "last_name": "Olsen",
        "email": "loop@example.com",
        "rank_pay_grade": "E-7",
        "rank_title": rank_for_pay_grade("E-7"),
        "current_installation_preset": "Fort Drum, NY",
        "gaining_installation": "Fort Leavenworth, KS",
        "move_window": "3–6 months",
        "spouse_career_field": "K-12 education / teaching",
        "num_children": 1,
        "child_age_ranges": ["High school (14–18)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Cat(s)"],
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2000,
        "housing_must_haves_selected": ["Good school district", "Pet-friendly"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Winter weather / heating costs"],
    },
}