"""Loop 6 profiles — Bragg/Stewart, Carson/Sill, Bliss/JBLM."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_G = {
    "e6_bragg_stewart_trades": {
        "first_name": "Derek",
        "last_name": "Foster",
        "email": "loop@example.com",
        "rank_pay_grade": "E-6",
        "rank_title": rank_for_pay_grade("E-6"),
        "current_installation_preset": "Fort Bragg, NC",
        "gaining_installation": "Fort Stewart, GA",
        "move_window": "1–3 months",
        "spouse_career_field": "Trades / skilled labor",
        "num_children": 1,
        "child_age_ranges": ["Middle school (11–13)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1700,
        "housing_must_haves_selected": ["Garage / covered parking", "Pet-friendly"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Pet deposit / breed restrictions"],
    },
    "o4_carson_sill_nurse": {
        "first_name": "Amanda",
        "last_name": "Reyes",
        "email": "loop@example.com",
        "rank_pay_grade": "O-4",
        "rank_title": rank_for_pay_grade("O-4"),
        "current_installation_preset": "Fort Carson, CO",
        "gaining_installation": "Fort Sill, OK",
        "move_window": "Within 30 days",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2100,
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Child has IEP / special education needs", "Tight PCS timeline"],
        "specific_concerns": "Elementary child has IEP — need IEP transfer meeting before school start",
    },
    "e4_bliss_jblm_student": {
        "first_name": "Jaylen",
        "last_name": "Carter",
        "email": "loop@example.com",
        "rank_pay_grade": "E-4",
        "rank_title": rank_for_pay_grade("E-4"),
        "current_installation_preset": "Fort Bliss, TX",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "move_window": "3–6 months",
        "spouse_career_field": "Student / continuing education",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1600,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Gate traffic / commute sensitivity"],
    },
}