"""V2 Loop 3 — E-4 Bliss/JBLM student+DITY, E-7 Gordon/Stewart trades, O-2 Sill/Hood no kids."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_J = {
    "e4_bliss_jblm_student_dity": {
        "first_name": "Isaiah",
        "last_name": "Brooks",
        "email": "loop@example.com",
        "rank_pay_grade": "E-4",
        "rank_title": rank_for_pay_grade("E-4"),
        "current_installation_preset": "Fort Bliss, TX",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "move_window": "3–6 months",
        "spouse_career_field": "Student / continuing education",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1650,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Gate traffic / commute sensitivity"],
    },
    "e7_gordon_stewart_trades": {
        "first_name": "Frank",
        "last_name": "Deluca",
        "email": "loop@example.com",
        "rank_pay_grade": "E-7",
        "rank_title": rank_for_pay_grade("E-7"),
        "current_installation_preset": "Fort Gordon, GA",
        "gaining_installation": "Fort Stewart, GA",
        "move_window": "1–3 months",
        "spouse_career_field": "Trades / skilled labor",
        "num_children": 1,
        "child_age_ranges": ["High school (14–18)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1800,
        "housing_must_haves_selected": ["Garage / covered parking", "Pet-friendly"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Pet deposit / breed restrictions"],
    },
    "o2_sill_hood_nokids": {
        "first_name": "Michelle",
        "last_name": "Torres",
        "email": "loop@example.com",
        "rank_pay_grade": "O-2",
        "rank_title": rank_for_pay_grade("O-2"),
        "current_installation_preset": "Fort Sill, OK",
        "gaining_installation": "Fort Hood, TX",
        "move_window": "Within 30 days",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1900,
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Professional licensure transfer", "Tight PCS timeline"],
    },
}