"""V2 Loop 1 — E-3 Stewart/Benning, O-3 Hood/JBLM remote, E-8 Benning/Campbell teacher+IEP."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_H = {
    "e3_stewart_benning_pets": {
        "first_name": "Ethan",
        "last_name": "Morales",
        "email": "loop@example.com",
        "rank_pay_grade": "E-3",
        "rank_title": rank_for_pay_grade("E-3"),
        "current_installation_preset": "Fort Stewart, GA",
        "gaining_installation": "Fort Benning, GA",
        "move_window": "Within 30 days",
        "spouse_career_field": "Not currently working — seeking employment",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1150,
        "housing_must_haves_selected": ["Pet-friendly"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Pet deposit / breed restrictions"],
    },
    "o3_hood_jblm_remote": {
        "first_name": "Lauren",
        "last_name": "Chen",
        "email": "loop@example.com",
        "rank_pay_grade": "O-3",
        "rank_title": rank_for_pay_grade("O-3"),
        "current_installation_preset": "Fort Hood, TX",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "move_window": "3–6 months",
        "spouse_career_field": "Remote / work-from-home professional",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2600,
        "housing_must_haves_selected": ["Strong internet / remote-work ready", "Good school district"],
        "primary_priority": "School quality",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Winter weather / heating costs"],
    },
    "e8_benning_campbell_teacher_iep": {
        "first_name": "Robert",
        "last_name": "Hawkins",
        "email": "loop@example.com",
        "rank_pay_grade": "E-8",
        "rank_title": rank_for_pay_grade("E-8"),
        "current_installation_preset": "Fort Benning, GA",
        "gaining_installation": "Fort Campbell, KY",
        "move_window": "1–3 months",
        "spouse_career_field": "K-12 education / teaching",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2200,
        "housing_must_haves_selected": ["Good school district"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Child has IEP / special education needs"],
        "specific_concerns": "Only our elementary child has an IEP — need district confirmation before lease",
    },
}