"""Loop 2 profiles — Bliss/Hood, Leavenworth/Stewart, W-3 Bragg."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_C = {
    "e5_bliss_hood_trades": {
        "first_name": "Jordan",
        "last_name": "Pierce",
        "email": "loop@example.com",
        "rank_pay_grade": "E-5",
        "rank_title": rank_for_pay_grade("E-5"),
        "current_installation_preset": "Fort Bliss, TX",
        "gaining_installation": "Fort Hood, TX",
        "move_window": "Within 30 days",
        "spouse_career_field": "Trades / skilled labor",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1400,
        "housing_must_haves_selected": ["Garage / covered parking"],
        "primary_priority": "Spouse career / quick employment",
        "secondary_priority": "Minimizing total costs",
        "num_vehicles": "1",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": [],
    },
    "w3_leavenworth_stewart_nurse": {
        "first_name": "Patricia",
        "last_name": "Nguyen",
        "email": "loop@example.com",
        "rank_pay_grade": "W-3",
        "rank_title": rank_for_pay_grade("W-3"),
        "current_installation_preset": "Fort Leavenworth, KS",
        "gaining_installation": "Fort Stewart, GA",
        "move_window": "3–6 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 3,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2100,
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": ["Need childcare immediately on arrival"],
    },
    "o3_bragg_bliss_remote": {
        "first_name": "Daniel",
        "last_name": "Webb",
        "email": "loop@example.com",
        "rank_pay_grade": "O-3",
        "rank_title": rank_for_pay_grade("O-3"),
        "current_installation_preset": "Fort Bragg, NC",
        "gaining_installation": "Fort Bliss, TX",
        "move_window": "1–3 months",
        "spouse_career_field": "Remote / work-from-home professional",
        "num_children": 2,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2200,
        "housing_must_haves_selected": ["Strong internet / remote-work ready", "Fenced yard"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Gate traffic / commute sensitivity"],
    },
}