"""Warmth loop 2 — E-2 short move, E-6 federal, O-2 remote no kids."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_N = {
    "e2_knox_benning_retail": {
        "first_name": "Aiden",
        "last_name": "Cole",
        "email": "loop@example.com",
        "rank_pay_grade": "E-2",
        "rank_title": rank_for_pay_grade("E-2"),
        "current_installation_preset": "Fort Knox, KY",
        "gaining_installation": "Fort Benning, GA",
        "move_window": "Within 30 days",
        "spouse_career_field": "Retail / hospitality / service",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 1100,
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Tight PCS timeline"],
    },
    "e6_drum_stewart_federal": {
        "first_name": "Marcus",
        "last_name": "Hale",
        "email": "loop@example.com",
        "rank_pay_grade": "E-6",
        "rank_title": rank_for_pay_grade("E-6"),
        "current_installation_preset": "Fort Drum, NY",
        "gaining_installation": "Fort Stewart, GA",
        "move_window": "1–3 months",
        "spouse_career_field": "Federal / government civilian",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "High school (14–18)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (under 50 lb)"],
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1750,
        "housing_must_haves_selected": ["Pet-friendly", "Good school district"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Pet deposit / breed restrictions"],
    },
    "o2_bliss_carson_remote": {
        "first_name": "Ryan",
        "last_name": "Park",
        "email": "loop@example.com",
        "rank_pay_grade": "O-2",
        "rank_title": rank_for_pay_grade("O-2"),
        "current_installation_preset": "Fort Bliss, TX",
        "gaining_installation": "Fort Carson, CO",
        "move_window": "3–6 months",
        "spouse_career_field": "Remote / work-from-home professional",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 2100,
        "housing_must_haves_selected": ["Strong internet / remote-work ready"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Gate traffic / commute sensitivity"],
    },
}