"""Warmth loop 1 — E-4 pets/no kids, O-3 teacher+IEP, W-2 nurse EFMP."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

BATCH_M = {
    "e4_carson_bliss_pets": {
        "first_name": "Diego",
        "last_name": "Ruiz",
        "email": "loop@example.com",
        "rank_pay_grade": "E-4",
        "rank_title": rank_for_pay_grade("E-4"),
        "current_installation_preset": "Fort Carson, CO",
        "gaining_installation": "Fort Bliss, TX",
        "move_window": "1–3 months",
        "spouse_career_field": "Retail / hospitality / service",
        "num_children": 0,
        "child_age_ranges": [],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Cat(s)"],
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "max_monthly_budget": 1450,
        "housing_must_haves_selected": ["Pet-friendly"],
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Fastest possible resettlement",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Pet deposit / breed restrictions"],
    },
    "o3_riley_campbell_teacher_iep": {
        "first_name": "Jennifer",
        "last_name": "Walsh",
        "email": "loop@example.com",
        "rank_pay_grade": "O-3",
        "rank_title": rank_for_pay_grade("O-3"),
        "current_installation_preset": "Fort Riley, KS",
        "gaining_installation": "Fort Campbell, KY",
        "move_window": "3–6 months",
        "spouse_career_field": "K-12 education / teaching",
        "num_children": 2,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)"],
        "has_pets": "No pets",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2300,
        "housing_must_haves_selected": ["Good school district"],
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": ["Child has IEP / special education needs"],
        "specific_concerns": "Only our elementary child has an IEP — need district confirmation before lease",
    },
    "w2_hood_jblm_nurse_efmp": {
        "first_name": "Teresa",
        "last_name": "Nguyen",
        "email": "loop@example.com",
        "rank_pay_grade": "W-2",
        "rank_title": rank_for_pay_grade("W-2"),
        "current_installation_preset": "Fort Hood, TX",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "move_window": "1–3 months",
        "spouse_career_field": "Healthcare / nursing",
        "num_children": 1,
        "child_age_ranges": ["Preschool (3–5)"],
        "has_pets": "No pets",
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "max_monthly_budget": 2200,
        "primary_priority": "School quality",
        "secondary_priority": "Spouse career / quick employment",
        "num_vehicles": "2",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["EFMP / medical care coordination", "Need childcare immediately on arrival"],
    },
}