"""Diverse stress-test form payloads — one unique soldier profile per loop."""

from __future__ import annotations

from components.form_options import rank_for_pay_grade

STRESS_SCENARIOS: dict[str, dict] = {
    "e6_benning_campbell_trades": {
        "first_name": "Andre",
        "last_name": "Mitchell",
        "email": "stress-test@example.com",
        "rank_pay_grade": "E-6",
        "rank_title": rank_for_pay_grade("E-6"),
        "current_installation_preset": "Fort Benning, GA",
        "current_installation_other": "",
        "gaining_installation": "Fort Campbell, KY",
        "gaining_installation_other": "",
        "move_window": "1–3 months",
        "move_flexibility": "Fixed — must align with reporting date",
        "spouse_career_field": "Trades / skilled labor",
        "spouse_career_other": "",
        "num_children": 3,
        "child_age_ranges": ["Elementary (6–10)", "Middle school (11–13)", "High school (14–18)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Dog (50 lb or more)"],
        "pet_details": "German Shepherd, 72 lbs — need fenced yard",
        "housing_preference": "Off-post — prefer renting/buying locally",
        "budget_mode": "Set a monthly budget cap",
        "budget_preset": "$1,600 – $2,000/mo",
        "max_monthly_budget": 1750,
        "housing_must_haves_selected": ["Fenced yard", "4+ bedrooms", "Short commute (under 20 min)"],
        "housing_must_haves_other": "",
        "primary_priority": "School quality",
        "secondary_priority": "Minimizing total costs",
        "other_priorities": "Oldest starts high school — cannot miss transfer window",
        "num_vehicles": "2",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": [
            "Child has IEP / special education needs",
            "Gate traffic / commute sensitivity",
            "Need childcare immediately on arrival",
        ],
        "specific_concerns": "Middle child has IEP — need district confirmation before lease",
    },
    "o3_bliss_jblm_nurse": {
        "first_name": "Catherine",
        "last_name": "Webb",
        "email": "stress-test@example.com",
        "rank_pay_grade": "O-3",
        "rank_title": rank_for_pay_grade("O-3"),
        "current_installation_preset": "Fort Bliss, TX",
        "current_installation_other": "",
        "gaining_installation": "Joint Base Lewis-McChord, WA",
        "gaining_installation_other": "",
        "move_window": "3–6 months",
        "move_flexibility": "Somewhat flexible (±2 weeks)",
        "spouse_career_field": "Healthcare / nursing",
        "spouse_career_other": "",
        "num_children": 2,
        "child_age_ranges": ["Preschool (3–5)", "Elementary (6–10)"],
        "has_pets": "No pets",
        "pet_types": [],
        "pet_details": "",
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Optimize for best value",
        "budget_preset": "$2,000+/mo",
        "max_monthly_budget": 2400,
        "housing_must_haves_selected": ["Strong internet / remote-work ready", "Short commute (under 20 min)"],
        "housing_must_haves_other": "",
        "primary_priority": "Minimizing total costs",
        "secondary_priority": "Spouse career / quick employment",
        "other_priorities": "WA nursing license — unsure of timeline",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": [
            "Professional licensure transfer",
            "Winter weather / heating costs",
        ],
        "specific_concerns": "First cross-country PCS with two kids — worried about rain and licensure",
    },
    "w2_leavenworth_bragg_federal": {
        "first_name": "David",
        "last_name": "Park",
        "email": "stress-test@example.com",
        "rank_pay_grade": "W-2",
        "rank_title": rank_for_pay_grade("W-2"),
        "current_installation_preset": "Fort Leavenworth, KS",
        "current_installation_other": "",
        "gaining_installation": "Fort Bragg, NC",
        "gaining_installation_other": "",
        "move_window": "Within 30 days",
        "move_flexibility": "Fixed — must align with reporting date",
        "spouse_career_field": "Federal / government civilian",
        "spouse_career_other": "",
        "num_children": 1,
        "child_age_ranges": ["Elementary (6–10)"],
        "has_pets": "No pets",
        "pet_types": [],
        "pet_details": "",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "budget_preset": "$1,600 – $2,000/mo",
        "max_monthly_budget": 1900,
        "housing_must_haves_selected": ["Short commute (under 20 min)"],
        "housing_must_haves_other": "",
        "primary_priority": "Fastest possible resettlement",
        "secondary_priority": "Minimizing total costs",
        "other_priorities": "Spouse has tentative USAJOBS referral — needs to stay on timeline",
        "num_vehicles": "1",
        "dity_interest": "No — prefer a full government move",
        "concern_flags": ["Tight PCS timeline"],
        "specific_concerns": "30-day report date — cannot afford serial house-hunting",
    },
    "e4_stewart_sill_childcare": {
        "first_name": "Jasmine",
        "last_name": "Cole",
        "email": "stress-test@example.com",
        "rank_pay_grade": "E-4",
        "rank_title": rank_for_pay_grade("E-4"),
        "current_installation_preset": "Fort Stewart, GA",
        "current_installation_other": "",
        "gaining_installation": "Fort Sill, OK",
        "gaining_installation_other": "",
        "move_window": "1–3 months",
        "move_flexibility": "Somewhat flexible (±2 weeks)",
        "spouse_career_field": "Retail / hospitality / service",
        "spouse_career_other": "",
        "num_children": 2,
        "child_age_ranges": ["Infant (0–2)", "Preschool (3–5)"],
        "has_pets": "Yes — we have pets",
        "pet_types": ["Cat(s)"],
        "pet_details": "Two indoor cats",
        "housing_preference": "Open to either — best overall fit",
        "budget_mode": "Set a monthly budget cap",
        "budget_preset": "$1,200 – $1,600/mo",
        "max_monthly_budget": 1400,
        "housing_must_haves_selected": ["Pet-friendly", "Short commute (under 20 min)"],
        "housing_must_haves_other": "",
        "primary_priority": "Fastest possible resettlement",
        "secondary_priority": "Minimizing total costs",
        "other_priorities": "Infant needs CDC slot — spouse wants to work part-time within 6 weeks",
        "num_vehicles": "1",
        "dity_interest": "Maybe — run the numbers for me",
        "concern_flags": [
            "Need childcare immediately on arrival",
            "Winter weather / heating costs",
        ],
        "specific_concerns": "Never lived in tornado alley — nervous about housing and insurance",
    },
    "e8_hood_benning_efmp": {
        "first_name": "Robert",
        "last_name": "Henderson",
        "email": "stress-test@example.com",
        "rank_pay_grade": "E-8",
        "rank_title": rank_for_pay_grade("E-8"),
        "current_installation_preset": "Fort Hood, TX",
        "current_installation_other": "",
        "gaining_installation": "Fort Benning, GA",
        "gaining_installation_other": "",
        "move_window": "3–6 months",
        "move_flexibility": "Very flexible — open to best timing",
        "spouse_career_field": "Student / continuing education",
        "spouse_career_other": "",
        "num_children": 1,
        "child_age_ranges": ["Middle school (11–13)"],
        "has_pets": "No pets",
        "pet_types": [],
        "pet_details": "",
        "housing_preference": "On-post — prefer government housing",
        "budget_mode": "Optimize for best value",
        "budget_preset": "$1,600 – $2,000/mo",
        "max_monthly_budget": 1850,
        "housing_must_haves_selected": ["Strong internet / remote-work ready", "Short commute (under 20 min)"],
        "housing_must_haves_other": "",
        "primary_priority": "School quality",
        "secondary_priority": "Fastest possible resettlement",
        "other_priorities": "Spouse starting online master's — needs quiet housing and solid internet",
        "num_vehicles": "2",
        "dity_interest": "Yes — I want to explore a DITY/PPM move",
        "concern_flags": [
            "EFMP / medical care coordination",
            "Child has IEP / special education needs",
        ],
        "specific_concerns": "EFMP enrollment must transfer cleanly — son has ongoing therapy",
    },
}

LOOP_SCENARIO_ORDER = [
    "e6_benning_campbell_trades",
    "o3_bliss_jblm_nurse",
    "w2_leavenworth_bragg_federal",
    "e4_stewart_sill_childcare",
    "e8_hood_benning_efmp",
]